### PR TITLE
Add more RSpec aliases

### PR DESCRIPTION
**Pull request by Bartuz**
Introducing `xfeature`, `ffeature` and `fscenario`

### CODE REVIEW

File: lib/capybara/rspec/features.rb [hunk 1]
```diff
@@ -21,9 +23,12 @@ def self.included(base)
           alias :background :before
           alias :scenario :it
           alias :xscenario :xit
+          alias :fscenario :fit
```
Comment (Bartuz) [inline lib/capybara/rspec/features.rb]: does RSpec 2.X has `fit` or `fdescribe` aliases? 

http://www.relishapp.com/rspec/rspec-core/v/2-14/docs/configuration/alias-example-to

**Comment by Bartuz** [comment]
How does the test output look like:
test_output

**Comment by Bartuz** [comment]
Only Ruby 1.9.3 build (the second one? there are two builds on 1.9.3) fails. https://travis-ci.org/jnicklas/capybara/jobs/96986194
with message: 
```
NoMethodError: undefined method `exclude_pattern=' for #<RSpec::Core::RakeTask:0x000000015f71b0`
```

Any assistance?

**Comment by twalpole** [comment]
As a guess RSpec 2.2 doesn't support exclude_pattern=   -- don't break out these tests into a separate task and just test for the metadata in the test rather than that true == true.

File: spec/rspec/features_focus_tag_spec.rb [hunk 2]
```diff
@@ -0,0 +1,18 @@
+require 'spec_helper'
+require 'capybara/rspec'
+
+RSpec.configuration.before(:each, { file_path: "./spec/rspec/features_spec.rb" } ) do
+  @in_filtered_hook = true
+end
+
+ffeature "if ffeature alises focused tag then" do
```
Comment (twalpole) [inline spec/rspec/features_focus_tag_spec.rb]: spelling - aliases

Comment (Bartuz) [inline spec/rspec/features_focus_tag_spec.rb]: :crying_cat_face:

**Comment by Bartuz** [comment]
@twalpole I have merged these tasks and refactored focus tag specs

File: lib/capybara/rspec/features.rb [hunk 3]
```diff
@@ -21,9 +23,12 @@ def self.included(base)
...
           alias :given :let
           alias :given! :let!
           alias :feature :describe
+          alias :xfeature :xdescribe
```
Comment (twalpole) [inline lib/capybara/rspec/features.rb]: The base version of RSpec we currently claim support for (2.2) doesn't support xdescribe -- don't add any of these changes for RSpec 2 - capybara will no longer support it in the next major release anyway

File: spec/rspec/features_spec.rb [hunk 4]
```diff
@@ -70,8 +70,18 @@ def current_example(context)
   end
 end
 
-feature "if xscenario aliases to pending then" do
-  xscenario "this test should be 'temporarily disabled with xscenario'" do
+xfeature "if xfeature aliases to pending then" do
```
Comment (twalpole) [inline spec/rspec/features_spec.rb]: This needs a condition so the test is not run for RSpec < 3  - probably the other additions too

**Comment by Bartuz** [comment]
rbx-2 uses rspec-core 3.4.1 and fails after removing rspec 2 aliases. need to investigate

File: spec/rspec/scenarios_spec.rb [hunk 5]
```diff
@@ -0,0 +1,20 @@
+require 'spec_helper'
+require 'capybara/rspec'
+
+RSpec.configuration.before(:each, { file_path: "./spec/rspec/features_spec.rb" } ) do
+  @in_filtered_hook = true
+end
+
+if RSpec::Core::Version::STRING.to_f >= 3.0 || RUBY_ENGINE == 'rbx'
```
Comment (Bartuz) [inline spec/rspec/scenarios_spec.rb]: @twalpole I don't know if it's good idea to put if statement for `rbx`. I'm unfamiliar with it at all. Do you think it's acceptable?

Comment (twalpole) [inline spec/rspec/scenarios_spec.rb]: I have no idea why 'rbx' would cause a failure here, and really don't want to skip testing on it without understanding exactly why it's failing

File: spec/rspec/scenarios_spec.rb [hunk 6]
```diff
@@ -0,0 +1,20 @@
+require 'spec_helper'
+require 'capybara/rspec'
+
+RSpec.configuration.before(:each, { file_path: "./spec/rspec/features_spec.rb" } ) do
```
Comment (twalpole) [inline spec/rspec/scenarios_spec.rb]: This isn't needed in this file is it?

Comment (Bartuz) [inline spec/rspec/scenarios_spec.rb]: Nice catch! Actually `@in_filtered_hook = true` was needed for rbnx tests! They pass now :)

**Comment by twalpole** [comment]
Ok looks like the tests pass, please squash this down to one commit

**Comment by Bartuz** [comment]
Should I force push to `bartuz/master` or create new PR?

**Comment by twalpole** [comment]
Just squash and force push

**Comment by Bartuz** [comment]
@twalpole thanks you assistance and patience! :)

**Comment by twalpole** [comment]
Thanks a lot!
