### ISSUE TITLE
`shared_connection` fix in readme no longer works with Rails 4.1.8

### ISSUE THREAD

**Issue by aaronjensen** [jnicklas/capybara#1447]
Specifically when doing a `ActiveRecord::Migration.maintain_test_schema!`

Raises:

```
/Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute': NoMethodError: undefined method `query' for nil:NilClass: DROP DATABASE IF EXISTS `app_test` /*application:AppName*/ (ActiveRecord::StatementInvalid)
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activesupport-4.1.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/rack-mini-profiler-0.9.2/lib/patches/sql_patches.rb:258:in `log_with_miniprofiler'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `execute'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/connection_adapters/mysql2_adapter.rb:228:in `execute'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/marginalia-1.1.4/lib/marginalia.rb:33:in `execute_with_marginalia'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:382:in `drop_database'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:356:in `recreate_database'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/connection_pool-1.0.0/lib/connection_pool.rb:95:in `block in method_missing'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/connection_pool-1.0.0/lib/connection_pool.rb:48:in `with'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/connection_pool-1.0.0/lib/connection_pool.rb:94:in `method_missing'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/tasks/mysql_database_tasks.rb:46:in `purge'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:144:in `purge'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:170:in `load_schema_for'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:185:in `block in load_schema_current'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:225:in `block in each_current_configuration'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:224:in `each'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:224:in `each_current_configuration'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:184:in `load_schema_current'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/migration.rb:394:in `load_schema_if_pending!'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/migration.rb:401:in `block in maintain_test_schema!'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/migration.rb:629:in `suppress_messages'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/migration.rb:406:in `method_missing'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/activerecord-4.1.8/lib/active_record/migration.rb:401:in `maintain_test_schema!'
        from /Users/u/Source/gemset/spec/spec_helper.rb:107:in `block (2 levels) in <top (required)>'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/rspec-core-3.0.2/lib/rspec/core/example.rb:294:in `instance_exec'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/rspec-core-3.0.2/lib/rspec/core/example.rb:294:in `instance_exec'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/rspec-core-3.0.2/lib/rspec/core/hooks.rb:349:in `run'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/rspec-core-3.0.2/lib/rspec/core/hooks.rb:410:in `block in run'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/rspec-core-3.0.2/lib/rspec/core/hooks.rb:410:in `each'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/rspec-core-3.0.2/lib/rspec/core/hooks.rb:410:in `run'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/rspec-core-3.0.2/lib/rspec/core/hooks.rb:485:in `run'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:111:in `block in run_specs'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/rspec-core-3.0.2/lib/rspec/core/reporter.rb:54:in `report'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:108:in `run_specs'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:86:in `run'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:70:in `run'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:38:in `invoke'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/gems/rspec-core-3.0.2/exe/rspec:4:in `<top (required)>'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/bin/rspec:23:in `load'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/bin/rspec:23:in `<main>'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/bin/ruby_executable_hooks:15:in `eval'
        from /Users/u/.rvm/gems/ruby-2.1.5@gemset/bin/ruby_executable_hooks:15:in `<main>'
```

This is "not a rails issue" because it's a monkey patch relying on rails internals. See: https://github.com/rails/rails/issues/17826

This change caused it to stop working: https://github.com/rails/rails/compare/v4.1.7.1...v4.1.8?diff=split&name=v4.1.8#diff-1452ba37bae4c4676b4288be7db09b8dR160

I'm not sure how to fix it just yet, so I'm just reporting it for now.

**Comment by turboladen** [comment]
@aaronjensen that worked for me too--thanks!

**Comment by onebree** [comment]
Is `maintain_test_schema` is issue? Did you run into the same problem if you disabled/removed that option? I am wondering because we use spring, which we configured to include the monkey patch. Otherwise if we run `bundle exec rspec` without spring, all tests including `js: true` fail.

Any threading issue went away with the following in the `config/spring.rb` file:
```ruby
Spring.after_fork do
  if Rails.env == "test"
    class ActiveRecord::Base
      mattr_accessor :shared_connection
      @@shared_connection = nil
      def self.connection
        @@shared_connection || ConnectionPool::Wrapper.new(size: 1) { retrieve_connection }
      end
    end
    ActiveRecord::Base.shared_connection = ActiveRecord::Base.connection
  end
end
```

Then we added the following to our `rails_helper.rb` file:
```ruby
RSpec.configure do |config|
  config.before(:suite) { User.acts_as_authentic { |c| c.maintain_sessions = false } }
end
```

**Comment by twalpole** [comment]
I've removed the suggestion from the README, it's too problematic to be a reasonable suggestion for beginning users of Capybara
